### ISSUE TITLE
when switch to "memcached" cache_mode, the client part need NOT to be configured

### ISSUE THREAD

**Issue by normann** [deviateltd/silverstripe-cacheable#12]
However, if you omit the 'client' part from the CacheableConfig, the framework throws an error when doing Clean/Rebuild task.

In my project, I have to make an work-around temperately like this:

```
CacheableConfig:
  cache_mode: "memcached"
  opts:
    memcached:
      servers:
        host: "localhost"
        port: "11211"
        weight: "1"
      client:
        9: "1"
        2: "1"
        16: true
```
