### ISSUE TITLE
Allow custom methods & properties via config

### ISSUE THREAD

**Issue by phptek** [deviateltd/silverstripe-cacheable#13]
The `CacheableSiteTree` and `CacheableSiteConfig` classes contain a minimum number of `$cacheable_functions` and `$cacheable_fields`, but projects may have additional requirements.

Allow projects to define YML based configuration, to augment the defaults, something similar to the following:

```
CacheableSiteTree:
  fields:
    - CustomFieldOne
    - CustomFieldTwo
  functions:
    - CustomFuncOne
    - CustomFuncTwo
```
