### ISSUE TITLE
Add shippable CI config

### ISSUE THREAD

**Issue by phptek** [deviateltd/silverstripe-cacheable#14]
Add YML config such that tests are run and docs are generated:
- Create shippable.yml file that runs tests and generates docs
- Docs should be re-generated each time a build is run using Doxygen
- README should display a "Shippable" icon, when unit-tests passed the last time they were run

**Comment by phptek** [comment]
Scrutinizer seems to have the ability to run unit tests also. Seeing as we wish to add code-quality metrics to our OS modules, why use a separate CI service like Travis/Shippable if Scrutinizer does what we need in the one SaaS?

**Comment by phptek** [comment]
I have had several goes at this without success using Shippable. Perhaps we should look at Travis instead?

**Comment by phptek** [comment]
SilverStripe Travis support works via the https://github.com/silverstripe-labs/silverstripe-travis-support module.

An example .travis.yml file might look like:

```
# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
language: php 
php: 
  - 5.3
  - 5.4
env:
  - DB=MYSQL CORE_RELEASE=3.1
matrix:
  include:
    - php: 5.3
      env: DB=MYSQL
    - php: 5.4
      env: DB=MYSQL

branches:
  master

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: 
  - phpunit silverstripe-cacheable/tests
```
